version: '3.4'

services:
  firebase_db:
    image: postgres:9.6.8
    volumes:
      - firebase_db_data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: firebase
      POSTGRES_PASSWORD: firebase
      POSTGRES_USER: firebase
      PGDATA: /var/lib/postgresql/data/pgdata
volumes:
  firebase_db_data:
    name: spdb-firebase-volume
